//! Generated protobuf types for the ROSQL gRPC interface.
//!
//! These types are generated by `tonic-build`/`prost-build` from the proto
//! files in `proto/rosql/v1/`. Generated into cargo's OUT_DIR at build time.

#[allow(clippy::all)]
#[allow(unused_imports)]
pub mod rosql_v1 {
    include!(concat!(env!("OUT_DIR"), "/rosql.v1.rs"));
}
