//! Generated protobuf types for the ROSQL gRPC interface.
//!
//! These types are generated by `prost-build` from the proto files in
//! `proto/rosql/v1/`. They define the contract between the `rosql-parser`
//! gRPC sidecar and the Go backend.
//!
//! Regenerate by running `cargo build` (the build.rs script handles generation).

#[allow(clippy::all)]
pub mod rosql_v1 {
    include!("rosql.v1.rs");
}
