// This file is @generated by prost-build.
/// A parsed ROSQL query.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RosqlQuery {
    #[prost(oneof = "rosql_query::Query", tags = "1, 2, 3")]
    pub query: ::core::option::Option<rosql_query::Query>,
}
/// Nested message and enum types in `ROSQLQuery`.
pub mod rosql_query {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Query {
        #[prost(message, tag = "1")]
        Standard(super::StandardQuery),
        #[prost(message, tag = "2")]
        Pipeline(super::PipelineQuery),
        #[prost(message, tag = "3")]
        Compound(super::CompoundQuery),
    }
}
/// Standard SQL-shaped query: SELECT ... FROM ... WHERE ...
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StandardQuery {
    #[prost(message, repeated, tag = "1")]
    pub selections: ::prost::alloc::vec::Vec<Selection>,
    #[prost(message, optional, tag = "2")]
    pub data_source: ::core::option::Option<DataSource>,
    #[prost(message, optional, tag = "3")]
    pub robot_scope: ::core::option::Option<RobotScope>,
    #[prost(message, optional, tag = "4")]
    pub conditions: ::core::option::Option<Condition>,
    #[prost(message, optional, tag = "5")]
    pub facet: ::core::option::Option<FacetClause>,
    #[prost(message, optional, tag = "6")]
    pub time_range: ::core::option::Option<TimeRange>,
    #[prost(enumeration = "TimeBasis", tag = "7")]
    pub time_basis: i32,
    #[prost(message, optional, tag = "8")]
    pub order_by: ::core::option::Option<OrderBy>,
    #[prost(uint64, optional, tag = "9")]
    pub limit: ::core::option::Option<u64>,
    #[prost(enumeration = "OutputFormat", tag = "10")]
    pub output_format: i32,
    #[prost(message, optional, tag = "11")]
    pub baseline: ::core::option::Option<Baseline>,
}
/// Pipeline query: FROM source | WHERE ... | FACET ...
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PipelineQuery {
    #[prost(message, repeated, tag = "1")]
    pub stages: ::prost::alloc::vec::Vec<PipelineStage>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PipelineStage {
    #[prost(
        oneof = "pipeline_stage::Stage",
        tags = "1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12"
    )]
    pub stage: ::core::option::Option<pipeline_stage::Stage>,
}
/// Nested message and enum types in `PipelineStage`.
pub mod pipeline_stage {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Stage {
        #[prost(message, tag = "1")]
        From(super::DataSource),
        #[prost(message, tag = "2")]
        Select(super::SelectStage),
        #[prost(message, tag = "3")]
        Where(super::Condition),
        #[prost(message, tag = "4")]
        Facet(super::FacetClause),
        #[prost(message, tag = "5")]
        Since(super::TimeRange),
        #[prost(enumeration = "super::TimeBasis", tag = "6")]
        Using(i32),
        #[prost(message, tag = "7")]
        OrderBy(super::OrderBy),
        #[prost(uint64, tag = "8")]
        Limit(u64),
        #[prost(enumeration = "super::OutputFormat", tag = "9")]
        Format(i32),
        #[prost(message, tag = "10")]
        CompareTo(super::Baseline),
        #[prost(message, tag = "11")]
        ForRobot(super::RobotScope),
        #[prost(message, tag = "12")]
        CompoundClause(super::CompoundClause),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SelectStage {
    #[prost(message, repeated, tag = "1")]
    pub selections: ::prost::alloc::vec::Vec<Selection>,
}
/// Compound query: MESSAGE JOURNEY, HEALTH(), ANOMALY(), etc.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CompoundQuery {
    #[prost(message, optional, tag = "1")]
    pub clause: ::core::option::Option<CompoundClause>,
    #[prost(message, optional, tag = "2")]
    pub robot_scope: ::core::option::Option<RobotScope>,
    #[prost(message, optional, tag = "3")]
    pub time_range: ::core::option::Option<TimeRange>,
    #[prost(enumeration = "TimeBasis", tag = "4")]
    pub time_basis: i32,
    #[prost(message, optional, tag = "5")]
    pub conditions: ::core::option::Option<Condition>,
    #[prost(message, optional, tag = "6")]
    pub facet: ::core::option::Option<FacetClause>,
    #[prost(message, optional, tag = "7")]
    pub order_by: ::core::option::Option<OrderBy>,
    #[prost(uint64, optional, tag = "8")]
    pub limit: ::core::option::Option<u64>,
    #[prost(enumeration = "OutputFormat", tag = "9")]
    pub output_format: i32,
    #[prost(message, optional, tag = "10")]
    pub baseline: ::core::option::Option<Baseline>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct DataSource {
    #[prost(oneof = "data_source::Source", tags = "1, 2")]
    pub source: ::core::option::Option<data_source::Source>,
}
/// Nested message and enum types in `DataSource`.
pub mod data_source {
    #[derive(Clone, Copy, PartialEq, ::prost::Oneof)]
    pub enum Source {
        #[prost(enumeration = "super::DataSourceType", tag = "1")]
        Type(i32),
        #[prost(enumeration = "super::TopicAliasType", tag = "2")]
        TopicAlias(i32),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Selection {
    #[prost(oneof = "selection::Selection", tags = "1, 2, 3, 4")]
    pub selection: ::core::option::Option<selection::Selection>,
}
/// Nested message and enum types in `Selection`.
pub mod selection {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Selection {
        /// SELECT *
        #[prost(bool, tag = "1")]
        Star(bool),
        /// field reference
        #[prost(string, tag = "2")]
        Field(::prost::alloc::string::String),
        /// function call
        #[prost(message, tag = "3")]
        Aggregation(super::AggregationCall),
        /// expr AS alias
        #[prost(message, tag = "4")]
        Aliased(::prost::alloc::boxed::Box<super::AliasedSelection>),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AliasedSelection {
    #[prost(message, optional, boxed, tag = "1")]
    pub expr: ::core::option::Option<::prost::alloc::boxed::Box<Selection>>,
    #[prost(string, tag = "2")]
    pub alias: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AggregationCall {
    #[prost(enumeration = "AggregationFunction", tag = "1")]
    pub function: i32,
    #[prost(message, repeated, tag = "2")]
    pub args: ::prost::alloc::vec::Vec<Expr>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Expr {
    #[prost(oneof = "expr::Expr", tags = "1, 2, 3, 4, 5, 6")]
    pub expr: ::core::option::Option<expr::Expr>,
}
/// Nested message and enum types in `Expr`.
pub mod expr {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Expr {
        #[prost(string, tag = "1")]
        Field(::prost::alloc::string::String),
        #[prost(message, tag = "2")]
        Literal(super::Literal),
        #[prost(message, tag = "3")]
        UnitValue(super::UnitValue),
        #[prost(message, tag = "4")]
        Aggregation(super::AggregationCall),
        #[prost(message, tag = "5")]
        FieldAccess(super::FieldAccess),
        #[prost(message, tag = "6")]
        BinaryOp(::prost::alloc::boxed::Box<super::BinaryOp>),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Literal {
    #[prost(oneof = "literal::Value", tags = "1, 2, 3, 4, 5")]
    pub value: ::core::option::Option<literal::Value>,
}
/// Nested message and enum types in `Literal`.
pub mod literal {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Value {
        #[prost(int64, tag = "1")]
        Integer(i64),
        #[prost(double, tag = "2")]
        Float(f64),
        #[prost(string, tag = "3")]
        StringValue(::prost::alloc::string::String),
        #[prost(bool, tag = "4")]
        Boolean(bool),
        /// always true when set
        #[prost(bool, tag = "5")]
        Null(bool),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UnitValue {
    /// value as written by the user
    #[prost(double, tag = "1")]
    pub raw_value: f64,
    /// unit symbol (e.g. "ms")
    #[prost(string, tag = "2")]
    pub unit: ::prost::alloc::string::String,
    /// SI-normalised value (e.g. 0.5)
    #[prost(double, tag = "3")]
    pub si_value: f64,
    /// SI base unit symbol (e.g. "s")
    #[prost(string, tag = "4")]
    pub si_unit: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FieldAccess {
    /// e.g. "fields"
    #[prost(string, tag = "1")]
    pub base: ::prost::alloc::string::String,
    /// e.g. "my_value"
    #[prost(string, tag = "2")]
    pub key: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BinaryOp {
    #[prost(message, optional, boxed, tag = "1")]
    pub left: ::core::option::Option<::prost::alloc::boxed::Box<Expr>>,
    #[prost(enumeration = "ArithmeticOp", tag = "2")]
    pub op: i32,
    #[prost(message, optional, boxed, tag = "3")]
    pub right: ::core::option::Option<::prost::alloc::boxed::Box<Expr>>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Condition {
    #[prost(oneof = "condition::Condition", tags = "1, 2, 3, 4, 5, 6, 7, 8, 9")]
    pub condition: ::core::option::Option<condition::Condition>,
}
/// Nested message and enum types in `Condition`.
pub mod condition {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Condition {
        #[prost(message, tag = "1")]
        Comparison(super::Comparison),
        #[prost(message, tag = "2")]
        And(::prost::alloc::boxed::Box<super::LogicalOp>),
        #[prost(message, tag = "3")]
        Or(::prost::alloc::boxed::Box<super::LogicalOp>),
        #[prost(message, tag = "4")]
        Not(::prost::alloc::boxed::Box<super::Condition>),
        #[prost(message, tag = "5")]
        IsNull(super::Expr),
        #[prost(message, tag = "6")]
        IsNotNull(super::Expr),
        #[prost(message, tag = "7")]
        InExpr(super::InExpr),
        #[prost(message, tag = "8")]
        Like(super::LikeExpr),
        #[prost(message, tag = "9")]
        Between(super::BetweenExpr),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Comparison {
    #[prost(message, optional, tag = "1")]
    pub left: ::core::option::Option<Expr>,
    #[prost(enumeration = "ComparisonOp", tag = "2")]
    pub op: i32,
    #[prost(message, optional, tag = "3")]
    pub right: ::core::option::Option<Expr>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LogicalOp {
    #[prost(message, optional, boxed, tag = "1")]
    pub left: ::core::option::Option<::prost::alloc::boxed::Box<Condition>>,
    #[prost(message, optional, boxed, tag = "2")]
    pub right: ::core::option::Option<::prost::alloc::boxed::Box<Condition>>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InExpr {
    #[prost(message, optional, tag = "1")]
    pub expr: ::core::option::Option<Expr>,
    #[prost(message, repeated, tag = "2")]
    pub values: ::prost::alloc::vec::Vec<Expr>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LikeExpr {
    #[prost(message, optional, tag = "1")]
    pub expr: ::core::option::Option<Expr>,
    #[prost(string, tag = "2")]
    pub pattern: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BetweenExpr {
    #[prost(message, optional, tag = "1")]
    pub expr: ::core::option::Option<Expr>,
    #[prost(message, optional, tag = "2")]
    pub low: ::core::option::Option<Expr>,
    #[prost(message, optional, tag = "3")]
    pub high: ::core::option::Option<Expr>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TimeRange {
    #[prost(oneof = "time_range::Range", tags = "1, 2")]
    pub range: ::core::option::Option<time_range::Range>,
}
/// Nested message and enum types in `TimeRange`.
pub mod time_range {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Range {
        #[prost(message, tag = "1")]
        Since(super::TimeExpr),
        #[prost(message, tag = "2")]
        Between(super::BetweenTime),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BetweenTime {
    #[prost(message, optional, tag = "1")]
    pub start: ::core::option::Option<TimeExpr>,
    #[prost(message, optional, tag = "2")]
    pub end: ::core::option::Option<TimeExpr>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TimeExpr {
    #[prost(oneof = "time_expr::Expr", tags = "1, 2, 3, 4")]
    pub expr: ::core::option::Option<time_expr::Expr>,
}
/// Nested message and enum types in `TimeExpr`.
pub mod time_expr {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Expr {
        #[prost(message, tag = "1")]
        Relative(super::RelativeTime),
        /// RFC 3339 timestamp
        #[prost(string, tag = "2")]
        Absolute(::prost::alloc::string::String),
        #[prost(message, tag = "3")]
        Epoch(super::UnixEpoch),
        #[prost(enumeration = "super::LifecycleAnchor", tag = "4")]
        Anchor(i32),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RelativeTime {
    #[prost(double, tag = "1")]
    pub amount: f64,
    /// "minutes", "hours", "days", etc.
    #[prost(string, tag = "2")]
    pub unit: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct UnixEpoch {
    #[prost(oneof = "unix_epoch::Precision", tags = "1, 2, 3")]
    pub precision: ::core::option::Option<unix_epoch::Precision>,
}
/// Nested message and enum types in `UnixEpoch`.
pub mod unix_epoch {
    #[derive(Clone, Copy, PartialEq, ::prost::Oneof)]
    pub enum Precision {
        /// 10-digit
        #[prost(uint64, tag = "1")]
        Seconds(u64),
        /// 13-digit
        #[prost(uint64, tag = "2")]
        Milliseconds(u64),
        /// 19-digit
        #[prost(uint64, tag = "3")]
        Nanoseconds(u64),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RobotScope {
    #[prost(oneof = "robot_scope::Scope", tags = "1, 2")]
    pub scope: ::core::option::Option<robot_scope::Scope>,
}
/// Nested message and enum types in `RobotScope`.
pub mod robot_scope {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Scope {
        /// FOR ROBOT 'robot_42'
        #[prost(string, tag = "1")]
        RobotId(::prost::alloc::string::String),
        /// FOR FLEET (always true when set)
        #[prost(bool, tag = "2")]
        Fleet(bool),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FacetClause {
    #[prost(string, tag = "1")]
    pub dimension: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OrderBy {
    #[prost(string, tag = "1")]
    pub field: ::prost::alloc::string::String,
    #[prost(enumeration = "SortDirection", tag = "2")]
    pub direction: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Baseline {
    #[prost(oneof = "baseline::Baseline", tags = "1, 2, 3, 4, 5")]
    pub baseline: ::core::option::Option<baseline::Baseline>,
}
/// Nested message and enum types in `Baseline`.
pub mod baseline {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Baseline {
        /// always true when set
        #[prost(bool, tag = "1")]
        LastWeek(bool),
        /// always true when set
        #[prost(bool, tag = "2")]
        Fleet(bool),
        /// COMPARE TO ROBOT 'robot_01'
        #[prost(string, tag = "3")]
        RobotId(::prost::alloc::string::String),
        /// always true when set
        #[prost(bool, tag = "4")]
        LastDeployment(bool),
        /// always true when set
        #[prost(bool, tag = "5")]
        CompareRobots(bool),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CompoundClause {
    #[prost(
        oneof = "compound_clause::Clause",
        tags = "1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11"
    )]
    pub clause: ::core::option::Option<compound_clause::Clause>,
}
/// Nested message and enum types in `CompoundClause`.
pub mod compound_clause {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Clause {
        #[prost(message, tag = "1")]
        During(super::DuringClause),
        #[prost(message, tag = "2")]
        MessageJourney(super::MessageJourneyClause),
        #[prost(message, tag = "3")]
        MessagePaths(super::MessagePathsClause),
        #[prost(message, tag = "4")]
        MessagePath(super::MessagePathClause),
        #[prost(message, tag = "5")]
        Trace(super::TraceClause),
        /// always true when set
        #[prost(bool, tag = "6")]
        ShowTraceBreakdown(bool),
        /// always true when set
        #[prost(bool, tag = "7")]
        Health(bool),
        #[prost(message, tag = "8")]
        Anomaly(super::AnomalyClause),
        #[prost(message, tag = "9")]
        PathDeviation(super::PathDeviationClause),
        #[prost(message, tag = "10")]
        Correlate(super::CorrelateClause),
        /// always true when set
        #[prost(bool, tag = "11")]
        ShowRecording(bool),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DuringClause {
    #[prost(message, optional, tag = "1")]
    pub inner_source: ::core::option::Option<DataSource>,
    #[prost(message, optional, tag = "2")]
    pub inner_conditions: ::core::option::Option<Condition>,
    #[prost(message, optional, tag = "3")]
    pub inner_time_range: ::core::option::Option<TimeRange>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MessageJourneyClause {
    #[prost(string, tag = "1")]
    pub trace_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MessagePathsClause {
    #[prost(string, tag = "1")]
    pub topic: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MessagePathClause {
    #[prost(string, tag = "1")]
    pub from_topic: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub to_node: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub show: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TraceClause {
    #[prost(string, tag = "1")]
    pub trace_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AnomalyClause {
    #[prost(string, tag = "1")]
    pub field: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub compared_to: ::core::option::Option<Baseline>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PathDeviationClause {
    #[prost(string, repeated, tag = "1")]
    pub show: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct CorrelateClause {
    #[prost(message, optional, tag = "1")]
    pub with_source: ::core::option::Option<DataSource>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum DataSourceType {
    Unspecified = 0,
    Logs = 1,
    SystemLogs = 2,
    Traces = 3,
    Metrics = 4,
    Diagnostics = 5,
    Topics = 6,
    Tf = 7,
    Heartbeats = 8,
    Recordings = 9,
    Events = 10,
}
impl DataSourceType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "DATA_SOURCE_TYPE_UNSPECIFIED",
            Self::Logs => "DATA_SOURCE_TYPE_LOGS",
            Self::SystemLogs => "DATA_SOURCE_TYPE_SYSTEM_LOGS",
            Self::Traces => "DATA_SOURCE_TYPE_TRACES",
            Self::Metrics => "DATA_SOURCE_TYPE_METRICS",
            Self::Diagnostics => "DATA_SOURCE_TYPE_DIAGNOSTICS",
            Self::Topics => "DATA_SOURCE_TYPE_TOPICS",
            Self::Tf => "DATA_SOURCE_TYPE_TF",
            Self::Heartbeats => "DATA_SOURCE_TYPE_HEARTBEATS",
            Self::Recordings => "DATA_SOURCE_TYPE_RECORDINGS",
            Self::Events => "DATA_SOURCE_TYPE_EVENTS",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "DATA_SOURCE_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "DATA_SOURCE_TYPE_LOGS" => Some(Self::Logs),
            "DATA_SOURCE_TYPE_SYSTEM_LOGS" => Some(Self::SystemLogs),
            "DATA_SOURCE_TYPE_TRACES" => Some(Self::Traces),
            "DATA_SOURCE_TYPE_METRICS" => Some(Self::Metrics),
            "DATA_SOURCE_TYPE_DIAGNOSTICS" => Some(Self::Diagnostics),
            "DATA_SOURCE_TYPE_TOPICS" => Some(Self::Topics),
            "DATA_SOURCE_TYPE_TF" => Some(Self::Tf),
            "DATA_SOURCE_TYPE_HEARTBEATS" => Some(Self::Heartbeats),
            "DATA_SOURCE_TYPE_RECORDINGS" => Some(Self::Recordings),
            "DATA_SOURCE_TYPE_EVENTS" => Some(Self::Events),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum TopicAliasType {
    Unspecified = 0,
    /// /odom
    Odom = 1,
    /// /joint_states
    JointStates = 2,
    /// /battery_state
    Battery = 3,
    /// /cmd_vel
    CmdVel = 4,
    /// /imu/data
    Imu = 5,
}
impl TopicAliasType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "TOPIC_ALIAS_TYPE_UNSPECIFIED",
            Self::Odom => "TOPIC_ALIAS_TYPE_ODOM",
            Self::JointStates => "TOPIC_ALIAS_TYPE_JOINT_STATES",
            Self::Battery => "TOPIC_ALIAS_TYPE_BATTERY",
            Self::CmdVel => "TOPIC_ALIAS_TYPE_CMD_VEL",
            Self::Imu => "TOPIC_ALIAS_TYPE_IMU",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "TOPIC_ALIAS_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "TOPIC_ALIAS_TYPE_ODOM" => Some(Self::Odom),
            "TOPIC_ALIAS_TYPE_JOINT_STATES" => Some(Self::JointStates),
            "TOPIC_ALIAS_TYPE_BATTERY" => Some(Self::Battery),
            "TOPIC_ALIAS_TYPE_CMD_VEL" => Some(Self::CmdVel),
            "TOPIC_ALIAS_TYPE_IMU" => Some(Self::Imu),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum AggregationFunction {
    Unspecified = 0,
    Count = 1,
    Sum = 2,
    Avg = 3,
    Min = 4,
    Max = 5,
    Percentile = 6,
    Stddev = 7,
    Rate = 8,
    Delta = 9,
    Derivative = 10,
    MovingAvg = 11,
    TopicRate = 12,
    NodeStatus = 13,
    Expected = 14,
    ActionSuccessRate = 15,
    Uptime = 16,
    ApproxCountDistinct = 17,
    ApproxPercentile = 18,
}
impl AggregationFunction {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "AGGREGATION_FUNCTION_UNSPECIFIED",
            Self::Count => "AGGREGATION_FUNCTION_COUNT",
            Self::Sum => "AGGREGATION_FUNCTION_SUM",
            Self::Avg => "AGGREGATION_FUNCTION_AVG",
            Self::Min => "AGGREGATION_FUNCTION_MIN",
            Self::Max => "AGGREGATION_FUNCTION_MAX",
            Self::Percentile => "AGGREGATION_FUNCTION_PERCENTILE",
            Self::Stddev => "AGGREGATION_FUNCTION_STDDEV",
            Self::Rate => "AGGREGATION_FUNCTION_RATE",
            Self::Delta => "AGGREGATION_FUNCTION_DELTA",
            Self::Derivative => "AGGREGATION_FUNCTION_DERIVATIVE",
            Self::MovingAvg => "AGGREGATION_FUNCTION_MOVING_AVG",
            Self::TopicRate => "AGGREGATION_FUNCTION_TOPIC_RATE",
            Self::NodeStatus => "AGGREGATION_FUNCTION_NODE_STATUS",
            Self::Expected => "AGGREGATION_FUNCTION_EXPECTED",
            Self::ActionSuccessRate => "AGGREGATION_FUNCTION_ACTION_SUCCESS_RATE",
            Self::Uptime => "AGGREGATION_FUNCTION_UPTIME",
            Self::ApproxCountDistinct => "AGGREGATION_FUNCTION_APPROX_COUNT_DISTINCT",
            Self::ApproxPercentile => "AGGREGATION_FUNCTION_APPROX_PERCENTILE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "AGGREGATION_FUNCTION_UNSPECIFIED" => Some(Self::Unspecified),
            "AGGREGATION_FUNCTION_COUNT" => Some(Self::Count),
            "AGGREGATION_FUNCTION_SUM" => Some(Self::Sum),
            "AGGREGATION_FUNCTION_AVG" => Some(Self::Avg),
            "AGGREGATION_FUNCTION_MIN" => Some(Self::Min),
            "AGGREGATION_FUNCTION_MAX" => Some(Self::Max),
            "AGGREGATION_FUNCTION_PERCENTILE" => Some(Self::Percentile),
            "AGGREGATION_FUNCTION_STDDEV" => Some(Self::Stddev),
            "AGGREGATION_FUNCTION_RATE" => Some(Self::Rate),
            "AGGREGATION_FUNCTION_DELTA" => Some(Self::Delta),
            "AGGREGATION_FUNCTION_DERIVATIVE" => Some(Self::Derivative),
            "AGGREGATION_FUNCTION_MOVING_AVG" => Some(Self::MovingAvg),
            "AGGREGATION_FUNCTION_TOPIC_RATE" => Some(Self::TopicRate),
            "AGGREGATION_FUNCTION_NODE_STATUS" => Some(Self::NodeStatus),
            "AGGREGATION_FUNCTION_EXPECTED" => Some(Self::Expected),
            "AGGREGATION_FUNCTION_ACTION_SUCCESS_RATE" => Some(Self::ActionSuccessRate),
            "AGGREGATION_FUNCTION_UPTIME" => Some(Self::Uptime),
            "AGGREGATION_FUNCTION_APPROX_COUNT_DISTINCT" => {
                Some(Self::ApproxCountDistinct)
            }
            "AGGREGATION_FUNCTION_APPROX_PERCENTILE" => Some(Self::ApproxPercentile),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ArithmeticOp {
    Unspecified = 0,
    Add = 1,
    Sub = 2,
    Mul = 3,
    Div = 4,
}
impl ArithmeticOp {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "ARITHMETIC_OP_UNSPECIFIED",
            Self::Add => "ARITHMETIC_OP_ADD",
            Self::Sub => "ARITHMETIC_OP_SUB",
            Self::Mul => "ARITHMETIC_OP_MUL",
            Self::Div => "ARITHMETIC_OP_DIV",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ARITHMETIC_OP_UNSPECIFIED" => Some(Self::Unspecified),
            "ARITHMETIC_OP_ADD" => Some(Self::Add),
            "ARITHMETIC_OP_SUB" => Some(Self::Sub),
            "ARITHMETIC_OP_MUL" => Some(Self::Mul),
            "ARITHMETIC_OP_DIV" => Some(Self::Div),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ComparisonOp {
    Unspecified = 0,
    Eq = 1,
    Neq = 2,
    Lt = 3,
    Gt = 4,
    Lte = 5,
    Gte = 6,
}
impl ComparisonOp {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "COMPARISON_OP_UNSPECIFIED",
            Self::Eq => "COMPARISON_OP_EQ",
            Self::Neq => "COMPARISON_OP_NEQ",
            Self::Lt => "COMPARISON_OP_LT",
            Self::Gt => "COMPARISON_OP_GT",
            Self::Lte => "COMPARISON_OP_LTE",
            Self::Gte => "COMPARISON_OP_GTE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "COMPARISON_OP_UNSPECIFIED" => Some(Self::Unspecified),
            "COMPARISON_OP_EQ" => Some(Self::Eq),
            "COMPARISON_OP_NEQ" => Some(Self::Neq),
            "COMPARISON_OP_LT" => Some(Self::Lt),
            "COMPARISON_OP_GT" => Some(Self::Gt),
            "COMPARISON_OP_LTE" => Some(Self::Lte),
            "COMPARISON_OP_GTE" => Some(Self::Gte),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum LifecycleAnchor {
    Unspecified = 0,
    LastDeployment = 1,
    LastRobotRestart = 2,
    LastActionFailure = 3,
    LastTopicDrop = 4,
    LastDiagnosticWarning = 5,
}
impl LifecycleAnchor {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "LIFECYCLE_ANCHOR_UNSPECIFIED",
            Self::LastDeployment => "LIFECYCLE_ANCHOR_LAST_DEPLOYMENT",
            Self::LastRobotRestart => "LIFECYCLE_ANCHOR_LAST_ROBOT_RESTART",
            Self::LastActionFailure => "LIFECYCLE_ANCHOR_LAST_ACTION_FAILURE",
            Self::LastTopicDrop => "LIFECYCLE_ANCHOR_LAST_TOPIC_DROP",
            Self::LastDiagnosticWarning => "LIFECYCLE_ANCHOR_LAST_DIAGNOSTIC_WARNING",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "LIFECYCLE_ANCHOR_UNSPECIFIED" => Some(Self::Unspecified),
            "LIFECYCLE_ANCHOR_LAST_DEPLOYMENT" => Some(Self::LastDeployment),
            "LIFECYCLE_ANCHOR_LAST_ROBOT_RESTART" => Some(Self::LastRobotRestart),
            "LIFECYCLE_ANCHOR_LAST_ACTION_FAILURE" => Some(Self::LastActionFailure),
            "LIFECYCLE_ANCHOR_LAST_TOPIC_DROP" => Some(Self::LastTopicDrop),
            "LIFECYCLE_ANCHOR_LAST_DIAGNOSTIC_WARNING" => {
                Some(Self::LastDiagnosticWarning)
            }
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum TimeBasis {
    Unspecified = 0,
    RosTime = 1,
    WallTime = 2,
}
impl TimeBasis {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "TIME_BASIS_UNSPECIFIED",
            Self::RosTime => "TIME_BASIS_ROS_TIME",
            Self::WallTime => "TIME_BASIS_WALL_TIME",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "TIME_BASIS_UNSPECIFIED" => Some(Self::Unspecified),
            "TIME_BASIS_ROS_TIME" => Some(Self::RosTime),
            "TIME_BASIS_WALL_TIME" => Some(Self::WallTime),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum SortDirection {
    Unspecified = 0,
    Asc = 1,
    Desc = 2,
}
impl SortDirection {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "SORT_DIRECTION_UNSPECIFIED",
            Self::Asc => "SORT_DIRECTION_ASC",
            Self::Desc => "SORT_DIRECTION_DESC",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "SORT_DIRECTION_UNSPECIFIED" => Some(Self::Unspecified),
            "SORT_DIRECTION_ASC" => Some(Self::Asc),
            "SORT_DIRECTION_DESC" => Some(Self::Desc),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum OutputFormat {
    Unspecified = 0,
    Table = 1,
    Timeseries = 2,
    Scalar = 3,
    TraceTree = 4,
    Graph = 5,
    Path = 6,
}
impl OutputFormat {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "OUTPUT_FORMAT_UNSPECIFIED",
            Self::Table => "OUTPUT_FORMAT_TABLE",
            Self::Timeseries => "OUTPUT_FORMAT_TIMESERIES",
            Self::Scalar => "OUTPUT_FORMAT_SCALAR",
            Self::TraceTree => "OUTPUT_FORMAT_TRACE_TREE",
            Self::Graph => "OUTPUT_FORMAT_GRAPH",
            Self::Path => "OUTPUT_FORMAT_PATH",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "OUTPUT_FORMAT_UNSPECIFIED" => Some(Self::Unspecified),
            "OUTPUT_FORMAT_TABLE" => Some(Self::Table),
            "OUTPUT_FORMAT_TIMESERIES" => Some(Self::Timeseries),
            "OUTPUT_FORMAT_SCALAR" => Some(Self::Scalar),
            "OUTPUT_FORMAT_TRACE_TREE" => Some(Self::TraceTree),
            "OUTPUT_FORMAT_GRAPH" => Some(Self::Graph),
            "OUTPUT_FORMAT_PATH" => Some(Self::Path),
            _ => None,
        }
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ParseRequest {
    #[prost(string, tag = "1")]
    pub query: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub options: ::core::option::Option<ParseOptions>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ParseOptions {
    /// If true, include source location spans in the AST nodes.
    #[prost(bool, tag = "1")]
    pub include_spans: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ParseResponse {
    #[prost(oneof = "parse_response::Result", tags = "1, 2")]
    pub result: ::core::option::Option<parse_response::Result>,
}
/// Nested message and enum types in `ParseResponse`.
pub mod parse_response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Result {
        #[prost(message, tag = "1")]
        Query(super::RosqlQuery),
        #[prost(message, tag = "2")]
        Error(super::ParseErrorDetail),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ParseErrorDetail {
    #[prost(string, tag = "1")]
    pub message: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub location: ::core::option::Option<SourceLocation>,
    /// Optional "did you mean?" suggestion.
    #[prost(string, tag = "3")]
    pub suggestion: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SourceLocation {
    #[prost(uint32, tag = "1")]
    pub line: u32,
    #[prost(uint32, tag = "2")]
    pub column: u32,
    #[prost(uint32, tag = "3")]
    pub offset: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ValidateRequest {
    #[prost(string, tag = "1")]
    pub query: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ValidateResponse {
    #[prost(bool, tag = "1")]
    pub valid: bool,
    #[prost(message, repeated, tag = "2")]
    pub errors: ::prost::alloc::vec::Vec<ValidationDiagnostic>,
    #[prost(message, repeated, tag = "3")]
    pub warnings: ::prost::alloc::vec::Vec<ValidationDiagnostic>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ValidationDiagnostic {
    #[prost(string, tag = "1")]
    pub message: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub location: ::core::option::Option<SourceLocation>,
    #[prost(enumeration = "DiagnosticSeverity", tag = "3")]
    pub severity: i32,
    #[prost(string, tag = "4")]
    pub suggestion: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetCompletionsRequest {
    #[prost(string, tag = "1")]
    pub query: ::prost::alloc::string::String,
    /// 0-based byte offset of the cursor position.
    #[prost(uint32, tag = "2")]
    pub cursor_position: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetCompletionsResponse {
    #[prost(message, repeated, tag = "1")]
    pub completions: ::prost::alloc::vec::Vec<Completion>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Completion {
    /// The text to insert.
    #[prost(string, tag = "1")]
    pub label: ::prost::alloc::string::String,
    /// Human-readable description.
    #[prost(string, tag = "2")]
    pub detail: ::prost::alloc::string::String,
    #[prost(enumeration = "CompletionKind", tag = "3")]
    pub kind: i32,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum DiagnosticSeverity {
    Unspecified = 0,
    Error = 1,
    Warning = 2,
    Info = 3,
}
impl DiagnosticSeverity {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "DIAGNOSTIC_SEVERITY_UNSPECIFIED",
            Self::Error => "DIAGNOSTIC_SEVERITY_ERROR",
            Self::Warning => "DIAGNOSTIC_SEVERITY_WARNING",
            Self::Info => "DIAGNOSTIC_SEVERITY_INFO",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "DIAGNOSTIC_SEVERITY_UNSPECIFIED" => Some(Self::Unspecified),
            "DIAGNOSTIC_SEVERITY_ERROR" => Some(Self::Error),
            "DIAGNOSTIC_SEVERITY_WARNING" => Some(Self::Warning),
            "DIAGNOSTIC_SEVERITY_INFO" => Some(Self::Info),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum CompletionKind {
    Unspecified = 0,
    Keyword = 1,
    DataSource = 2,
    Field = 3,
    Function = 4,
    Unit = 5,
}
impl CompletionKind {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "COMPLETION_KIND_UNSPECIFIED",
            Self::Keyword => "COMPLETION_KIND_KEYWORD",
            Self::DataSource => "COMPLETION_KIND_DATA_SOURCE",
            Self::Field => "COMPLETION_KIND_FIELD",
            Self::Function => "COMPLETION_KIND_FUNCTION",
            Self::Unit => "COMPLETION_KIND_UNIT",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "COMPLETION_KIND_UNSPECIFIED" => Some(Self::Unspecified),
            "COMPLETION_KIND_KEYWORD" => Some(Self::Keyword),
            "COMPLETION_KIND_DATA_SOURCE" => Some(Self::DataSource),
            "COMPLETION_KIND_FIELD" => Some(Self::Field),
            "COMPLETION_KIND_FUNCTION" => Some(Self::Function),
            "COMPLETION_KIND_UNIT" => Some(Self::Unit),
            _ => None,
        }
    }
}
/// Query result envelope — all ROSQL query results share this structure.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryResult {
    /// The output format of the result.
    #[prost(enumeration = "OutputFormat", tag = "1")]
    pub format: i32,
    /// The original ROSQL query text.
    #[prost(string, tag = "2")]
    pub query: ::prost::alloc::string::String,
    /// When the query was executed.
    #[prost(message, optional, tag = "3")]
    pub executed_at: ::core::option::Option<::prost_types::Timestamp>,
    /// Execution time in milliseconds.
    #[prost(uint64, tag = "4")]
    pub duration_ms: u64,
    /// Number of rows/items returned.
    #[prost(uint64, tag = "5")]
    pub row_count: u64,
    /// Whether the result was truncated (e.g. by LIMIT or max_rows).
    #[prost(bool, tag = "6")]
    pub truncated: bool,
    /// Format-specific result data.
    #[prost(oneof = "query_result::Data", tags = "10, 11, 12, 13, 14, 15")]
    pub data: ::core::option::Option<query_result::Data>,
}
/// Nested message and enum types in `QueryResult`.
pub mod query_result {
    /// Format-specific result data.
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Data {
        #[prost(message, tag = "10")]
        Table(super::TableResult),
        #[prost(message, tag = "11")]
        Timeseries(super::TimeseriesResult),
        #[prost(message, tag = "12")]
        Scalar(super::ScalarResult),
        #[prost(message, tag = "13")]
        TraceTree(super::TraceTreeResult),
        #[prost(message, tag = "14")]
        Graph(super::GraphResult),
        #[prost(message, tag = "15")]
        Path(super::PathResult),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TableResult {
    #[prost(message, repeated, tag = "1")]
    pub columns: ::prost::alloc::vec::Vec<ColumnMeta>,
    #[prost(message, repeated, tag = "2")]
    pub rows: ::prost::alloc::vec::Vec<Row>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ColumnMeta {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    /// "string", "number", "timestamp", etc.
    #[prost(string, tag = "2")]
    pub data_type: ::prost::alloc::string::String,
    /// display unit, if applicable
    #[prost(string, tag = "3")]
    pub unit: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Row {
    #[prost(message, repeated, tag = "1")]
    pub values: ::prost::alloc::vec::Vec<::prost_types::Value>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TimeseriesResult {
    /// The time bucket interval (e.g. "1 minute").
    #[prost(string, tag = "1")]
    pub interval: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub series: ::prost::alloc::vec::Vec<TimeSeries>,
    #[prost(string, tag = "3")]
    pub unit: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TimeSeries {
    /// Labels identifying this series (e.g. robot_id, node).
    #[prost(map = "string, string", tag = "1")]
    pub labels: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(message, repeated, tag = "2")]
    pub points: ::prost::alloc::vec::Vec<TimePoint>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct TimePoint {
    #[prost(message, optional, tag = "1")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(double, tag = "2")]
    pub value: f64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ScalarResult {
    #[prost(double, tag = "1")]
    pub value: f64,
    #[prost(string, tag = "2")]
    pub unit: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub label: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TraceTreeResult {
    #[prost(message, repeated, tag = "1")]
    pub roots: ::prost::alloc::vec::Vec<SpanNode>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SpanNode {
    #[prost(string, tag = "1")]
    pub trace_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub span_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub parent_span_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub span_name: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub service_name: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "6")]
    pub start_time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(uint64, tag = "7")]
    pub duration_ns: u64,
    #[prost(string, tag = "8")]
    pub status: ::prost::alloc::string::String,
    #[prost(map = "string, string", tag = "9")]
    pub attributes: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    #[prost(message, repeated, tag = "10")]
    pub children: ::prost::alloc::vec::Vec<SpanNode>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GraphResult {
    #[prost(message, repeated, tag = "1")]
    pub nodes: ::prost::alloc::vec::Vec<GraphNode>,
    #[prost(message, repeated, tag = "2")]
    pub edges: ::prost::alloc::vec::Vec<GraphEdge>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GraphNode {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// "node", "topic", "action", etc.
    #[prost(string, tag = "2")]
    pub r#type: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub label: ::prost::alloc::string::String,
    #[prost(map = "string, string", tag = "4")]
    pub metadata: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GraphEdge {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub from: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub to: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub label: ::prost::alloc::string::String,
    #[prost(map = "string, string", tag = "5")]
    pub metadata: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PathResult {
    #[prost(message, repeated, tag = "1")]
    pub actual_path: ::prost::alloc::vec::Vec<PathPoint>,
    #[prost(message, repeated, tag = "2")]
    pub planned_path: ::prost::alloc::vec::Vec<PathPoint>,
    #[prost(message, optional, tag = "3")]
    pub deviation: ::core::option::Option<PathDeviation>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct PathPoint {
    #[prost(message, optional, tag = "1")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(double, tag = "2")]
    pub x: f64,
    #[prost(double, tag = "3")]
    pub y: f64,
    #[prost(double, tag = "4")]
    pub theta: f64,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct PathDeviation {
    #[prost(double, tag = "1")]
    pub max_m: f64,
    #[prost(double, tag = "2")]
    pub avg_m: f64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FieldRegistry {
    #[prost(message, repeated, tag = "1")]
    pub fields: ::prost::alloc::vec::Vec<FieldDefinition>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FieldDefinition {
    /// The ROSQL field name (e.g. "duration", "node", "publish_rate").
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    /// The source table (e.g. "otel_traces", "otel_metrics").
    #[prost(string, tag = "2")]
    pub source: ::prost::alloc::string::String,
    /// The actual column or expression mapping (e.g. "Duration",
    /// "SpanAttributes\['ros.node'\]", "Value WHERE MetricName = '...'").
    #[prost(string, tag = "3")]
    pub column_mapping: ::prost::alloc::string::String,
    /// The field's data type.
    #[prost(enumeration = "FieldType", tag = "4")]
    pub r#type: i32,
    /// The storage unit (e.g. "ns" for nanoseconds, "Hz", "B/s").
    /// Empty if the field has no unit.
    #[prost(string, tag = "5")]
    pub storage_unit: ::prost::alloc::string::String,
    /// The unit support tier for this field.
    #[prost(enumeration = "UnitTier", tag = "6")]
    pub unit_tier: i32,
    /// Human-readable description for autocomplete tooltips.
    #[prost(string, tag = "7")]
    pub description: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum FieldType {
    Unspecified = 0,
    String = 1,
    Integer = 2,
    Float = 3,
    Boolean = 4,
    Timestamp = 5,
    Map = 6,
    Array = 7,
}
impl FieldType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "FIELD_TYPE_UNSPECIFIED",
            Self::String => "FIELD_TYPE_STRING",
            Self::Integer => "FIELD_TYPE_INTEGER",
            Self::Float => "FIELD_TYPE_FLOAT",
            Self::Boolean => "FIELD_TYPE_BOOLEAN",
            Self::Timestamp => "FIELD_TYPE_TIMESTAMP",
            Self::Map => "FIELD_TYPE_MAP",
            Self::Array => "FIELD_TYPE_ARRAY",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "FIELD_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "FIELD_TYPE_STRING" => Some(Self::String),
            "FIELD_TYPE_INTEGER" => Some(Self::Integer),
            "FIELD_TYPE_FLOAT" => Some(Self::Float),
            "FIELD_TYPE_BOOLEAN" => Some(Self::Boolean),
            "FIELD_TYPE_TIMESTAMP" => Some(Self::Timestamp),
            "FIELD_TYPE_MAP" => Some(Self::Map),
            "FIELD_TYPE_ARRAY" => Some(Self::Array),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum UnitTier {
    /// Unspecified.
    Unspecified = 0,
    /// Robot Ops-controlled columns — full unit support, storage unit
    /// documented in field registry.
    UnitTier1 = 1,
    /// ROS2 standard message fields — SI assumed per REP-103.
    UnitTier2 = 2,
    /// Custom fields — unit suffix rejected at parse time with clear error.
    UnitTier3 = 3,
}
impl UnitTier {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "UNIT_TIER_UNSPECIFIED",
            Self::UnitTier1 => "UNIT_TIER_1",
            Self::UnitTier2 => "UNIT_TIER_2",
            Self::UnitTier3 => "UNIT_TIER_3",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "UNIT_TIER_UNSPECIFIED" => Some(Self::Unspecified),
            "UNIT_TIER_1" => Some(Self::UnitTier1),
            "UNIT_TIER_2" => Some(Self::UnitTier2),
            "UNIT_TIER_3" => Some(Self::UnitTier3),
            _ => None,
        }
    }
}
